spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://140.143.227.55/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true


